name: Build and Test

on: 
  push:
    branches:
      - "master"
  pull_request:
    

jobs:
  gradle:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.3
    
    - name: Execute Gradle build
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew runTests